VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Specify a base box
    config.vm.box = "ubuntu/trusty64"
    
    # Set up port forwarding
    config.vm.network :forwarded_port, guest: 5601, host: 5601, auto_correct: true

    # Set up shared directories
    #config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

    # VirtualBox properties
    config.vm.provider "virtualbox" do |v|
        v.name = "elkbox"
        v.customize ["modifyvm", :id, "--memory", "1024"]
    end

    # Specify provisioner
    config.vm.provision "shell" do |s|
        s.path = "setup.sh"
    end

	# Forward display port
	config.ssh.forward_x11 = true

end